site_name: netcorepal-cloud-framework
site_description: A tactical framework for Domain-Driven Design based on ASP.NET Core.
site_author: NetCorePal #作者名
site_url: https://netcorepal.github.io/netcorepal-cloud-framework  #网站地址
copyright: Copyright &copy; 2024 NetCorePal # 左下角的版权声明

repo_name: "GitHub"
repo_url: "https://github.com/netcorepal/netcorepal-cloud-framework"
edit_uri: "edit/master/docs/content"
docs_dir: "content"

theme:
  name: material

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: netcorepal
      repo: netcorepal-cloud-framework
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: index.md
  - 入门: 
    - 创建项目: getting-started/getting-started.md
    - 项目结构: getting-started/project-structure.md
    - 开发流程: getting-started/development-process.md 
  - DDD原则: rules-of-ddd/rules-of-ddd.md
  - 关于AI: about-ai.md
  - 领域层:
    - 强类型ID: domain/strong-typed-id.md
    - 领域模型: domain/domain-entity.md
    - 领域事件: domain/domain-event.md
    # - 值对象: domain/domain-value-object.md
  - ID生成器:
    - Snowflake: id-generator/snowflake.md
    - Etcd: id-generator/etcd-worker-id-generator.md
  - 数据访问:
    - 仓储: data/repository.md
    - UnitOfWork: data/unit-of-work.md
  - 事务处理: transactions/transactions.md
  - 事件处理:
    - 领域事件处理器: events/domain-event-handler.md
    - 集成事件处理器: events/integration-event-handler.md
    - 集成事件转换器: events/integration-converter.md
  - 服务发现: 
    - 服务发现客户端: service-discovery/service-discovery-client.md
    - Kubernetes: service-discovery/k8s-service-discovery-provider.md
  - 上下文传递: 
    - 上下文访问器: context/context-accessor.md
    - AspNetCore: context/aspnetcore-context-processor.md
    - CAP: context/cap-context-processor.md
  - 并发控制:
    - 乐观锁-行版本号: concurrency/row-version.md
    - 悲观锁-Redis锁: concurrency/redis-lock.md
    - 命令锁: concurrency/command-lock.md
  - 多环境:
    - 环境上下文: env/env-context.md
    - 环境服务选择器: env/env-service-selector.md
    - CAP环境事件订阅器: env/env-cap-subscribe-filter.md
  - AspNetCore扩展:
    - 异常处理: aspnetcore/exception-handling.md
    - 数据响应: aspnetcore/response-data.md